#+TITLE: EMACS can do that ?

  - The website “[[https://vscodecandothat.com/][VSCodeCanDoThat.com]]” talk about 35 /amazing points/ than VSCode can do.
  - I think EMACS can do all this stuff... And more !
  - It this project works, why not building a website ? emacsCanDoThat.com ?
  - The project just start...

* Table of Contents                                 :TOC:
:PROPERTIES:
:VISIBILITY: all
:END:

- [[#0-refactor-promises-to-asyncawait][0. Refactor Promises to Async/Await]]
- [[#1-balance-inwardoutward][1. Balance Inward/Outward]]
- [[#2-pull-requests][2. Pull Requests]]
- [[#x-feature][X. Feature]]

* 0. Refactor Promises to Async/Await

#+begin_quote
  Refactor promises in TypeScript into Async/Await. This includes multiple then
  statements, Promise.all() and Promise.race(). Requires TypeScript 3.1.1.
#+end_quote

*[[https://github.com/magnars/js2-refactor.el][js2-refactor.el]]* /A JavaScript refactoring library for emacs/

This is a collection of small refactoring functions to further the idea of a
JavaScript IDE in Emacs that started with js2-mode.

* 1. Balance Inward/Outward

#+begin_quote
  You can select a whole tag in VS Code by using the balance inward and balance
  outward Emmet commands. It’s helpful to bind these commands to keyboard
  shortcuts, like Ctrl + Shift + Up Arrow for Balance Outward and Ctrl + Shift +
  Down Arrow for Balance Inward.
#+end_quote

* 2. Pull Requests

#+begin_quote
  The Github Pull Requests extension from Github allows you to view and interact
  with your Pull Requests directly from within VS Code.
#+end_quote

*[[https://magit.vc/][magit]]* /Magit is an interface to the version control system Git, implemented as an Emacs package/

Magit aspires to be a complete Git porcelain. While we cannot (yet) claim that
Magit wraps and improves upon each and every Git command, it is complete enough
to allow even experienced Git users to perform almost all of their daily version
control tasks directly from within Emacs. While many fine Git clients exist,
only Magit and Git itself deserve to be called porcelains.

* X. Feature

#+begin_quote
  Feature Description
#+end_quote

*[[https://github.com/magnars/feature.el][feature.el]]* /Feature one line summary/

Detailed feature description, including tables, videos, etc.
